
export enum Errors {
  INVALID_TOKEN = 'INVALID_TOKEN',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  USER_DOES_NOT_EXIST = 'USER_DOES_NOT_EXIST',
  INCORRECT_PASSWORD = 'INCORRECT_PASSWORD',
  REQUIRES_LOGIN = 'REQUIRES_LOGIN',
  NOT_ENOUGH_RIGHTS = 'NOT_ENOUGH_RIGHTS',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
}