
// Helper enum for all availabe rights
export enum Right {
  USERS_CREATE = "USERS_CREATE",
  USERS_UPDATE = "USERS_UPDATE",
  USERS_DELETE = "USERS_DELETE",
  ROLES_CREATE = "ROLES_CREATE",
  ROLES_UPDATE = "ROLES_UPDATE",
  ROLES_DELETE = "ROLES_DELETE",
  TASKS_CREATE = "TASKS_CREATE",
  TASKS_UPDATE = "TASKS_UPDATE",
  TASKS_DELETE = "TASKS_DELETE",
  PROJECTS_CREATE = "PROJECTS_CREATE",
  PROJECTS_UPDATE = "PROJECTS_UPDATE",
  PROJECTS_DELETE = "PROJECTS_DELETE",
}