import { PubSub } from "graphql-subscriptions";

export const pubsub = new PubSub();

export enum Events {
  USERS_UPDATE = 'USERS_UPDATE',
  ROLES_UPDATE = 'ROLES_UPDATE',
  TASKS_UPDATE = 'TASKS_UPDATE',
  PROJECTS_UPDATE = 'PROJECTS_UPDATE',
  CURRENT_USER_UPDATED = 'CURRENT_USER_UPDATED',
  CURRENT_USER_TASKS_UPDATED = 'CURRENT_USER_TASKS_UPDATED',
  CURRENT_USER_PROJECTS_UPDATED = 'CURRENT_USER_PROJECTS_UPDATED',
}